services:
  postgres:
    container_name: clean-nest-2
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: clean_nest_2
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
